export const CATEGORIES = [
  {
    id: "tabiqueria",
    name: "Tabiquería",
    icon: "🧱",
    projects: [
      {
        id: "tabique-madera-f30",
        name: "Tabique interior madera F-30 con doble placa",
        unit: "m²",
        description: "Tabique interior con estructura de madera 2x3, aislación y placa de yeso laminado doble cara.",
        technicalSpec:
          "Estructura de montantes de madera 2x3 con soleras superior e inferior. Aislación con lana mineral 50mm. Revestimiento con volcanita 10mm doble cara.",
        constructiveSolution:
          "Sistema de tabique seco con estructura de madera estructural reforzada para cumplir F-30.",
        materials: [
          { item: "Madera 2x3 estructural", unit: "m", quantity: 50, observation: "Montantes y soleras" },
          { item: "Volcanita 10mm", unit: "m²", quantity: 22, observation: "Revestimiento doble cara" },
          { item: "Lana mineral 50mm", unit: "m²", quantity: 20, observation: "Aislación interior" },
          { item: "Tornillos para volcanita", unit: "kg", quantity: 2.5, observation: "Fijación de placas" },
        ],
        regulations: ["MINVU ED17", "OGUC Art. 4.3.7", "NCh 934 (Fuego)", "NCh 853 (Térmico)"],
        costPerM2: { materials: 12500, labor: 8500, equipment: 1200, total: 22200 },
      },
      {
        id: "tabique-metal-f60",
        name: "Tabique metal stud F-60",
        unit: "m²",
        description:
          "Tabique con estructura metálica perfilería Cold-form, con aislación superior y doble placa tipo fuego.",
        technicalSpec: "Estructura con perfiles Cold-form, aislación lana mineral 75mm, doble volcanita tipo FM 15mm.",
        constructiveSolution: "Sistema de tabique seco con metal stud para mayor resistencia al fuego.",
        materials: [
          { item: "Perfil metal stud 75mm", unit: "m", quantity: 45, observation: "Estructura portante" },
          { item: "Volcanita tipo FM 15mm", unit: "m²", quantity: 24, observation: "Revestimiento doble cara fuego" },
          { item: "Lana mineral 75mm", unit: "m²", quantity: 20, observation: "Aislación térmica" },
        ],
        regulations: ["MINVU ED17", "OGUC Art. 4.3.7", "NCh 934 (Fuego F-60)"],
        costPerM2: { materials: 18500, labor: 10200, equipment: 1500, total: 30200 },
      },
      {
        id: "tabique-acustico",
        name: "Tabique divisor acústico 45 dB",
        unit: "m²",
        description: "Tabique especial con aislación acústica mejorada para cumplir 45 dB de atenuación.",
        technicalSpec: "Doble estructura con perfiles metal, lana mineral 100mm en cavidad, placas resilientes.",
        constructiveSolution: "Sistema acústico con doble cavidad y material absorbente de alto rendimiento.",
        materials: [
          { item: "Lana mineral 100mm", unit: "m²", quantity: 22, observation: "Aislación acústica premium" },
          { item: "Cinta resiliente", unit: "m", quantity: 50, observation: "Desacoplamiento acústico" },
        ],
        regulations: ["NCh 963 (Acústica)", "OGUC Art. 4.1.10"],
        costPerM2: { materials: 16000, labor: 11500, equipment: 1800, total: 29300 },
      },
      {
        id: "tabique-f60-acustico",
        name: "Tabique F-60 con doble placa acústica",
        unit: "m²",
        description: "Tabique con aislación acústica mejorada y placa tipo FM",
        technicalSpec: "Metal stud 75mm, lana mineral 100mm, volcanita FM doble cara",
        constructiveSolution: "Sistema acústico avanzado para espacios comerciales",
        materials: [
          { item: "Perfil metal stud 75mm", unit: "m", quantity: 45, observation: "Estructura" },
          { item: "Lana mineral 100mm", unit: "m²", quantity: 20, observation: "Aislación" },
          { item: "Volcanita FM 15mm", unit: "m²", quantity: 24, observation: "Fuego y acústica" },
        ],
        regulations: ["MINVU ED17", "NCh 934", "NCh 963"],
        costPerM2: { materials: 22000, labor: 12500, equipment: 2000, total: 36500 },
        author: "Constructora Delta",
        rating: 4.8,
      },
      {
        id: "tabique-madera-f15-economico",
        name: "Tabique interior madera F-15 económico",
        unit: "m²",
        description: "Tabique básico para divisiones interiores de bajo costo",
        technicalSpec: "Madera 2x2 con una placa de volcanita",
        constructiveSolution: "Sistema simple y económico para particiones",
        materials: [
          { item: "Madera 2x2", unit: "m", quantity: 35, observation: "Estructura básica" },
          { item: "Volcanita 10mm", unit: "m²", quantity: 12, observation: "Revestimiento simple" },
          { item: "Lana mineral 25mm", unit: "m²", quantity: 10, observation: "Aislación mínima" },
        ],
        regulations: ["MINVU ED17", "OGUC Art. 4.3.7"],
        costPerM2: { materials: 8500, labor: 5200, equipment: 800, total: 14500 },
        author: "Carpintería Moderna",
        rating: 4.3,
      },
    ],
  },
  {
    id: "lozas",
    name: "Estructuras y Loza",
    icon: "📦",
    projects: [
      {
        id: "loza-h25-12cm",
        name: "Loza hormigón H-25 12 cm",
        unit: "m²",
        description: "Losa de hormigón armado de 12 cm de espesor, H-25, con armadura standard.",
        technicalSpec: "Hormigón H-25 con armadura 2φ8 mm cada 20 cm ambas direcciones.",
        constructiveSolution: "Losa monolítica armada con hormigón premezclado.",
        materials: [
          { item: "Hormigón H-25", unit: "m³", quantity: 0.12, observation: "Hormigón premezclado" },
          { item: "Acero φ8 mm", unit: "kg", quantity: 3.5, observation: "Armadura" },
          { item: "Moldaje madera", unit: "m²", quantity: 1.2, observation: "Reutilizable" },
        ],
        regulations: ["MINVU ED15", "OGUC Art. 5.1", "NCh 430 (Hormigón)"],
        costPerM2: { materials: 14200, labor: 9500, equipment: 2100, total: 25800 },
      },
      {
        id: "radier-simple",
        name: "Radier simple 10 cm",
        unit: "m²",
        description: "Radier de hormigón simple sin armadura de 10 cm para usos no estructurales.",
        technicalSpec: "Hormigón simple H-15 con polietileno bajo y gravilla compactada.",
        constructiveSolution: "Base de fundación simple para pisos.",
        materials: [
          { item: "Hormigón H-15", unit: "m³", quantity: 0.1, observation: "Hormigón premezclado" },
          { item: "Base granular 10cm", unit: "m²", quantity: 1, observation: "Compactada" },
          { item: "Polietileno", unit: "m²", quantity: 1.05, observation: "Aislante humedad" },
        ],
        regulations: ["MINVU ED15", "OGUC Art. 5.2"],
        costPerM2: { materials: 8500, labor: 5200, equipment: 1400, total: 15100 },
      },
      {
        id: "loza-h30-espesor-15cm-con-isolante",
        name: "Loza H-30 espesor 15cm con isolante",
        unit: "m²",
        description: "Losa de hormigón armado reforzado con aislación térmica integral",
        technicalSpec: "Hormigón H-30, armadura densa 2φ10mm, poliestireno expandido 80mm",
        constructiveSolution: "Losa monolítica con aislación térmica para pisos superiores",
        materials: [
          { item: "Hormigón H-30", unit: "m³", quantity: 0.15, observation: "Premezclado" },
          { item: "Acero φ10 mm", unit: "kg", quantity: 5.5, observation: "Armadura densa" },
          { item: "Poliestireno expandido 80mm", unit: "m²", quantity: 1, observation: "Aislación térmica" },
          { item: "Moldaje metálico", unit: "m²", quantity: 1.2, observation: "Reutilizable" },
        ],
        regulations: ["MINVU ED15", "NCh 430", "NCh 853"],
        costPerM2: { materials: 18500, labor: 11200, equipment: 2800, total: 32500 },
        author: "Inmobiliaria Horizonte",
        rating: 4.6,
      },
      {
        id: "radier-reforzado-con-malla-estructural",
        name: "Radier reforzado con malla estructural",
        unit: "m²",
        description: "Radier con armadura de acero para mayor durabilidad",
        technicalSpec: "Hormigón H-20 10cm con malla acero φ6mm cada 20cm",
        constructiveSolution: "Base reforzada para pisos con mayor solicitud",
        materials: [
          { item: "Hormigón H-20", unit: "m³", quantity: 0.1, observation: "Hormigón" },
          { item: "Malla acero φ6mm", unit: "kg", quantity: 1.8, observation: "Armadura" },
          { item: "Base granular", unit: "m²", quantity: 1, observation: "Compactada" },
        ],
        regulations: ["MINVU ED15", "NCh 430"],
        costPerM2: { materials: 10500, labor: 6200, equipment: 1300, total: 18000 },
        author: "Fundaciones Andinas",
        rating: 4.5,
      },
    ],
  },
  {
    id: "pavimentos",
    name: "Pavimentos Urbanos",
    icon: "🛣️",
    projects: [
      {
        id: "vereda-hormigon-simple",
        name: "Vereda hormigón simple 7 cm",
        unit: "m²",
        description: "Vereda de hormigón simple para uso peatonal estándar.",
        technicalSpec: "Hormigón H-20 con espesor 7 cm sobre base compactada.",
        constructiveSolution: "Sistema simple de pavimento rígido.",
        materials: [
          { item: "Hormigón H-20", unit: "m³", quantity: 0.07, observation: "Hormigón premezclado" },
          { item: "Base granular 10cm", unit: "m²", quantity: 1, observation: "Compactada" },
        ],
        regulations: ["MINVU ED18", "OGUC Art. 7.1", "Manual de Carreteras Vol 3"],
        costPerM2: { materials: 6800, labor: 4200, equipment: 1100, total: 12100 },
      },
      {
        id: "calle-asfalto-5cm",
        name: "Pavimento asfalto 5 cm + base granular",
        unit: "m²",
        description: "Pavimento asfáltico de 5 cm sobre base granular de 15 cm.",
        technicalSpec: "Asfalto AC-20 con base granular compactada al 100% Proctor.",
        constructiveSolution: "Sistema flexible de pavimento asfáltico.",
        materials: [
          { item: "Asfalto AC-20", unit: "ton", quantity: 0.11, observation: "5 cm espesor" },
          { item: "Base granular", unit: "m³", quantity: 0.15, observation: "Compactada" },
        ],
        regulations: ["Manual de Carreteras Vol 3", "OGUC Art. 7.2"],
        costPerM2: { materials: 9200, labor: 5800, equipment: 1500, total: 16500 },
      },
      {
        id: "pavimento-mixto-asfalto-vereda-hormigon",
        name: "Pavimento mixto asfálto + vereda hormigón",
        unit: "m²",
        description: "Sistema combinado de pavimento flexible y rígido para vías urbanas",
        technicalSpec: "Asfalto AC-20 5cm + vereda hormigón H-20 7cm con base de 15cm",
        constructiveSolution: "Pavimento integrado con separación de secciones",
        materials: [
          { item: "Asfalto AC-20", unit: "ton", quantity: 0.11, observation: "Capa de rodadura" },
          { item: "Hormigón H-20", unit: "m³", quantity: 0.07, observation: "Vereda" },
          { item: "Base granular", unit: "m³", quantity: 0.15, observation: "Compactada 100% Proctor" },
        ],
        regulations: ["Manual de Carreteras Vol 3", "OGUC Art. 7.1", "OGUC Art. 7.2"],
        costPerM2: { materials: 11200, labor: 6800, equipment: 1800, total: 19800 },
        author: "Vialidad Urbana SpA",
        rating: 4.7,
      },
    ],
  },
  {
    id: "electricidad",
    name: "Electricidad y Corrientes Débiles",
    icon: "⚡",
    projects: [
      {
        id: "instalacion-vivienda-60m2",
        name: "Instalación eléctrica completa vivienda 60 m²",
        unit: "unidad",
        description: "Instalación eléctrica completa para vivienda de 60 m², incluyendo tablero y distribución.",
        technicalSpec: "Tablero principal 2x20 elementos, canalizaciones EMT, enchufes y puntos de iluminación.",
        constructiveSolution: "Sistema de distribución eléctrica domiciliaria con normativa SEC.",
        materials: [
          { item: "Tablero eléctrico 2x20", unit: "unidad", quantity: 1, observation: "Principal" },
          { item: "Canalización EMT 20mm", unit: "m", quantity: 150, observation: "Distribución" },
          { item: "Cableado 2.5mm²", unit: "m", quantity: 200, observation: "Circuitos" },
        ],
        regulations: ["SEC (Superintendencia de Electricidad)", "OGUC Art. 4.2", "NCh 4/2003"],
        costPerM2: { materials: 185000, labor: 120000, equipment: 25000, total: 330000 },
      },
    ],
  },
  {
    id: "sanitarias",
    name: "Obras Sanitarias",
    icon: "🚰",
    projects: [
      {
        id: "fosa-septica-600l",
        name: "Fosa séptica prefabricada 600L",
        unit: "unidad",
        description: "Fosa séptica prefabricada de polietileno de 600 litros.",
        technicalSpec: "Cámara única prefabricada con tratamiento dual.",
        constructiveSolution: "Sistema de tratamiento individual de aguas grises.",
        materials: [
          { item: "Fosa séptica prefabricada 600L", unit: "unidad", quantity: 1, observation: "Polietileno" },
          { item: "Tubería dren 100mm", unit: "m", quantity: 20, observation: "Sistema de infiltración" },
        ],
        regulations: ["OGUC Art. 4.5.1", "NCh 1333 (Aguas residuales)", "MINSAL"],
        costPerM2: { materials: 280000, labor: 60000, equipment: 15000, total: 355000 },
      },
    ],
  },
]

export type Project = (typeof CATEGORIES)[0]["projects"][0]

export const USER_PROJECTS = [
  {
    id: "user-tabique-f60-acustico",
    name: "Tabique F-60 con doble placa acústica",
    unit: "m²",
    description: "Tabique con aislación acústica mejorada y placa tipo FM",
    technicalSpec: "Metal stud 75mm, lana mineral 100mm, volcanita FM doble cara",
    constructiveSolution: "Sistema acústico avanzado para espacios comerciales",
    materials: [
      { item: "Perfil metal stud 75mm", unit: "m", quantity: 45, observation: "Estructura" },
      { item: "Lana mineral 100mm", unit: "m²", quantity: 20, observation: "Aislación" },
      { item: "Volcanita FM 15mm", unit: "m²", quantity: 24, observation: "Fuego y acústica" },
    ],
    regulations: ["MINVU ED17", "NCh 934", "NCh 963"],
    costPerM2: { materials: 22000, labor: 12500, equipment: 2000, total: 36500 },
    author: "Constructora Delta",
    rating: 4.8,
  },
  {
    id: "user-tabique-madera-f15-economico",
    name: "Tabique interior madera F-15 económico",
    unit: "m²",
    description: "Tabique básico para divisiones interiores de bajo costo",
    technicalSpec: "Madera 2x2 con una placa de volcanita",
    constructiveSolution: "Sistema simple y económico para particiones",
    materials: [
      { item: "Madera 2x2", unit: "m", quantity: 35, observation: "Estructura básica" },
      { item: "Volcanita 10mm", unit: "m²", quantity: 12, observation: "Revestimiento simple" },
      { item: "Lana mineral 25mm", unit: "m²", quantity: 10, observation: "Aislación mínima" },
    ],
    regulations: ["MINVU ED17", "OGUC Art. 4.3.7"],
    costPerM2: { materials: 8500, labor: 5200, equipment: 800, total: 14500 },
    author: "Carpintería Moderna",
    rating: 4.3,
  },
  {
    id: "user-loza-h30-espesor-15cm",
    name: "Loza H-30 espesor 15cm con isolante",
    unit: "m²",
    description: "Losa de hormigón armado reforzado con aislación térmica integral",
    technicalSpec: "Hormigón H-30, armadura densa 2φ10mm, poliestireno expandido 80mm",
    constructiveSolution: "Losa monolítica con aislación térmica para pisos superiores",
    materials: [
      { item: "Hormigón H-30", unit: "m³", quantity: 0.15, observation: "Premezclado" },
      { item: "Acero φ10 mm", unit: "kg", quantity: 5.5, observation: "Armadura densa" },
      { item: "Poliestireno expandido 80mm", unit: "m²", quantity: 1, observation: "Aislación térmica" },
      { item: "Moldaje metálico", unit: "m²", quantity: 1.2, observation: "Reutilizable" },
    ],
    regulations: ["MINVU ED15", "NCh 430", "NCh 853"],
    costPerM2: { materials: 18500, labor: 11200, equipment: 2800, total: 32500 },
    author: "Inmobiliaria Horizonte",
    rating: 4.6,
  },
  {
    id: "user-radier-reforzado",
    name: "Radier reforzado con malla estructural",
    unit: "m²",
    description: "Radier con armadura de acero para mayor durabilidad",
    technicalSpec: "Hormigón H-20 10cm con malla acero φ6mm cada 20cm",
    constructiveSolution: "Base reforzada para pisos con mayor solicitud",
    materials: [
      { item: "Hormigón H-20", unit: "m³", quantity: 0.1, observation: "Hormigón" },
      { item: "Malla acero φ6mm", unit: "kg", quantity: 1.8, observation: "Armadura" },
      { item: "Base granular", unit: "m²", quantity: 1, observation: "Compactada" },
    ],
    regulations: ["MINVU ED15", "NCh 430"],
    costPerM2: { materials: 10500, labor: 6200, equipment: 1300, total: 18000 },
    author: "Fundaciones Andinas",
    rating: 4.5,
  },
  {
    id: "user-pavimento-mixto",
    name: "Pavimento mixto asfálto + vereda hormigón",
    unit: "m²",
    description: "Sistema combinado de pavimento flexible y rígido para vías urbanas",
    technicalSpec: "Asfalto AC-20 5cm + vereda hormigón H-20 7cm con base de 15cm",
    constructiveSolution: "Pavimento integrado con separación de secciones",
    materials: [
      { item: "Asfalto AC-20", unit: "ton", quantity: 0.11, observation: "Capa de rodadura" },
      { item: "Hormigón H-20", unit: "m³", quantity: 0.07, observation: "Vereda" },
      { item: "Base granular", unit: "m³", quantity: 0.15, observation: "Compactada 100% Proctor" },
    ],
    regulations: ["Manual de Carreteras Vol 3", "OGUC Art. 7.1", "OGUC Art. 7.2"],
    costPerM2: { materials: 11200, labor: 6800, equipment: 1800, total: 19800 },
    author: "Vialidad Urbana SpA",
    rating: 4.7,
  },
]
